#!/bin/csh
# $Header: /cluster/animal/users/mhollen/scripts/fc_map_combine_bin,v 1.3 2010/04/20 16:50:34 mhollen Exp $
# $Log: fc_map_combine_bin,v $
# Revision 1.3  2010/04/20 16:50:34  mhollen
# too many updates to keep track of
#
# Revision 1.2  2010/03/08 22:07:21  mhollen
# i forget what i changed.
#
# Revision 1.1  2010/03/04 19:47:25  mhollen
# added ROIcreate, fc_map*, and vol2surf
#
# small updates to fc_analysis and fcfast
#
set idstr = '$Id: fc_map_combine_bin,v 1.3 2010/04/20 16:50:34 mhollen Exp $'

########################################################################################################
##  This program computes a timecourse from a seed region and correlates this ROI with all other voxels
########################################################################################################
ROI:

#set echo 
set subjects = ($1)
set wrkdir = $cwd
set region = ($2) 
set regname = ($3)
set thresh = $4
set grpname = $5
set regnumber = ${#region}
set format = "0x72+"

COMBINE_BIN:

if (! -e $wrkdir/GROUP_STATS/$grpname) mkdir -p $wrkdir/GROUP_STATS/$grpname
    @ k = 1
    while ($k <= $regnumber)
	pushd GROUP_STATS/$grpname
	    set lst_bin = "YOUNG_N"${#subjects}"_zfrm_"$regname[$k]_bin.lst
	    if (-e $lst_bin) /bin/rm $lst_bin; touch $lst_bin
	    echo "begin making image average expectation for $regname[$k]"
		foreach subject ($subjects)
		    source /$wrkdir/$subject/scripts/*params
		    set srcdir = $wrkdir/$subject/fcMRI_ANALYSIS/$grpname
		    set filen = $srcdir/$subject"_"$ppstr"_g7_bpss_resid_"$regname[$k]"_corcoef_zfrm"
		    set file = ${filen}'.nii.gz'
		    set outfile = ${filen}'_bin'
		    region_nifti 0 -12 22 -rad 180 -val 1 -thresh $thresh -i ${file} -o ${outfile}
		    /bin/mv ${outfile}*reg180mm*.nii.gz ${outfile}.nii.gz
		    echo ${outfile}'.nii.gz' >> ${lst_bin}
		end
	    imgopr_nifti -aYOUNG_N"${#subjects}"_$regname[$k]"_g7_zfrm_bin_sum" -l${lst_bin} -Z  #add -u?
	    #rho2z_nifti YOUNG_N"${#subjects}"_$regname[$k]"_g7_zfrm_avg" -r
	 popd      
    @ k++
    end
exit


