#!/bin/bash

function usage {

   echo " ______ _____   __  __          _____   "
   echo "|  ____/ ____| |  \/  |   /\   |  __ \  "
   echo "| |__ | |      | \  / |  /  \  | |__) | "
   echo "|  __|| |      | |\/| | / /\ \ |  ___/  ~ v2.0"
   echo "| |   | |____  | |  | |/ ____ \| |      "
   echo "|_|    \_____| |_|  |_/_/    \_\_|      "
   echo ""                                  
   echo "FC_MAP generates seeded functional connectivity maps in MNI152 space. Maps"
   echo "are given as Fisher's z, an r-to-z transformation (Fisher, 1915). Use the "
   echo "freesurfer tool mri_vol2surf to project values to cortex for visualization."
   echo ""
   echo "More documentation:"
   echo "  https://gate.nmr.mgh.harvard.edu/wiki/bradmci/index.php/NRG_Functional_Connectivity_Tools"
   echo "GitHub:"
   echo "  https://github.com/mrstepanovic/bradmci"
   echo ""
   echo "REQUIRED:"
   echo "  -S  <subj>    Subject IDs (use multiple in quotes to compare groups)"
   echo "  -R  <file>    ROI file locations"
   echo "  -N  <name>    ROI names (default is ROI file name)"
   echo ""
   echo "  OR"
   echo ""
   echo "  -s  <subjid>  File containing subject IDs"         
   echo "  -r  <paths>   File containing list of ROI files"
   echo "  -n  <names>   File containing list of ROI names"
   echo ""
   echo "EXAMPLE: (1) ./fc_map -S \"sub1 sub2 sub3\" -R \"roi1 roi2\" -N \"name1 name2\" \\"
   echo "                -G language_network"
   echo "         (2) ./fc_map -S \"sub1 sub2 sub3\" -R \"roi1 roi2\" -N \"name1 name2\" \\"
   echo "                -G language_network -g"
   echo ""
   echo "OPTIONS:"
   echo "  -u  <file>    Run file list (found in <subject>/<file>"
   echo "  -i            Generate unique connectivity map for each run, rather than each session"
  #echo "  -f            Project group results to fsaverage surface TODO"
  #echo "  -q            Create screenshot of group results on fsaverage surface TODO"
   echo "  -G  <name>    Analysis name, default 'FC'. Use a unique identifier for your analysis."
   echo "  -g            Create a group average map (must be run *after* individual maps are made)"
   echo "  -k  <fwhm>    Smoothing kernel size (default is 6mm)"
   echo "  -b            Create a group binarized map (set threshold with -t)"
   echo "  -t  <thresh>  Binarized map threshold (z-transform; use with -b; default is 0.2)"
   echo "  -h            Help"
   echo ""
   echo "COVARIATE ANALYSIS (new): Compute voxel-wise correlation between Fisher's z maps and"
   echo "                an additional measure (eg. IQ, TrailsB score, PASS subscale score, etc.)."
   echo "                Each measure will be correlated with voxelwise connectivity strength for "
   echo "                each seed."
   echo "  -m  <file>    Comma-separated covariates file, with column header. For example:"
   echo "                  SUBJECT, MEAS1, MEAS2"
   echo "                  SUBJECT001, 5, 6"
   echo "                  SUBJECT002, 7, 9"
   echo "  -M  <MEAS>    Column header from above (-m) representing a measure to be correlated "
   echo "                (multiples are okay). If left out, all fields are used from -m file. "
   echo "  -x            Skip subject-level fc_map generation (use with -m)"
#   echo "  -X            Skip FC map if does not exist (individual). Use with -m TODO"
   echo "  -v            Skip group-level fc_map generation (use with -m)"
   echo ""
   #echo "  -p           Submit parallel jobs to cluster (will need to enter password) TODO"
   echo "EXAMPLE: (1) ./fc_map -s group1.list -s group2.list \\"
   echo "                -r roi_files.list \\"
   echo "                -n roi_names.list \\"
   echo "                -m NEO_depression_score.txt"
   echo "                -G salience_network_vs_NEO_depression"
   echo "         (2) ./fc_map -s group1.list -s group2.list \\"
   echo "                -r roi_files.list \\"
   echo "                -n roi_names.list \\"
   echo "                -m NEO_depression_score.txt"
   echo "                -G salience_network_vs_NEO_depression \\"
   echo "                -g "
   echo ""
}

SUBJECTSfile=""
ROIsfile=""
ROInamesfile=""
ROInames=""
SUBJECTS=""
ROIs=""
THRESH="0.2"
GRPNAME="$(whoami)_fc"
FRAMES="72"
SMOOTH=6;
MEASFILE=""
MEASCORRFIELDS=""
SINGLEMAPS=1
SKIPMAPS=0
SKIPMAPSEXIST=0
SKIPGROUP=0
GROUPAVG=""
BRAINMASK="/cluster/animal/users/mhollen/mni/MNI152lin_T1_2mm_brain_mask.nii.gz"

while getopts "s:S:r:R:n:N:t:G:T:k:u:m:M:g b h c i x v X f " o ; do
    case $o in
         s ) SUBJECTSfile="$SUBJECTSfile $OPTARG";;
	 S ) SUBJECTS=$OPTARG;;
	 r ) ROIsfile=$OPTARG;;
	 R ) ROIs=$OPTARG;;
	 n ) ROInamesfile=$OPTARG;;
	 N ) ROInames=$OPTARG;;
	 m ) MEASFILE=$OPTARG;;
	 M ) MEASCORRFIELDS="${MEASCORRFIELDS}${OPTARG} ";;
	 t ) THRESH=$OPTARG;;
	 g ) GROUPAVG=1;;
	 G ) GRPNAME=$OPTARG;;
	 b ) GROUPBIN=1;;
	 c ) SINGLEMAPS=1;;
	 T ) FRAMES=$OPTARG;;
	 k ) SMOOTH=$OPTARG;;
	 i ) SEPARATE=1;;
         f ) FSPROJECT=1;;
	 u ) RUNFILE=$OPTARG;;
	 x ) SKIPMAPS=1;;
	 X ) SKIPMAPSEXIST=1;;
	 v ) SKIPGROUP=1;;
	 h ) usage; exit 0;;
	 * ) echo "Unkown argument "$o"." exit 1;
    esac
done

if [ $# -eq 0 ]; then
   usage; exit 0;
fi

NUMSUBJECTFILES=0
if [ "$SUBJECTS" == "" ]; then
    for f in $(echo $SUBJECTSfile); do
	if [ ! -r $f ]; then
	    echo "Error: cannot open subjects file: $f. (-h for help)"; exit 1;
	fi
    	SUBJECTS="$SUBJECTS $(cat $f | xargs)";
	SUBJECTGROUPS[$NUMSUBJECTFILES]="$(cat $f | xargs)"
	SUBJECTGROUPNAMES[$NUMSUBJECTFILES]="$(basename ${f})"
	NUMSUBJECTFILES=$((NUMSUBJECTFILES+1));
    done
    if [ "$(echo $SUBJECTS | xargs)" == "" ]; then
    	echo "Error: no subjects found."; exit 1;
    fi
    if [[ $NUMSUBJECTFILES -gt 2 ]];then
    	echo "Error: sorry, only support for 2 subject groups in glm (as of right now)."; exit 1;
    fi
    echo "SUBJECTS: $SUBJECTS";
    echo "  # SUBJECT GROUPS: $NUMSUBJECTFILES"
fi

if [ "$ROIs" == "" ]; then
    if [ ! -r $ROIsfile ]; then
	echo "Error: cannot open ROI file: $ROIsfile. (-h for help)"; exit 1;
    fi
    ROIs=$( cat $ROIsfile | xargs);
    echo "ROIs: $ROIs";
fi

if [ "$ROInames" == "" ]; then
    if [ ! -r $ROInamesfile ]; then
	echo "Error: cannot open ROI names file: $ROInamesfile. (-h for help)"; exit 1;
    fi
    ROInames=$( cat $ROInamesfile | xargs);
    echo "ROI labels: $ROInames";
fi

if [ $SKIPMAPS -eq 1 ]; then
    echo " *** Skipping FC  *** "
    SINGLEMAPS=""
fi

if [ $SKIPGROUP -eq 1 ]; then
    echo " *** Skippping Group Map *** "
    GROUPAVG=""
fi

if [[ $NUMSUBJECTFILES -gt 1 ]]; then
    echo "SUBJECT GROUPS:"
    for x in $(seq 0 $((${#SUBJECTGROUPS[*]} - 1))); do 
	echo "* GROUP $x (${SUBJECTGROUPNAMES[x]}): ${SUBJECTGROUPS[x]}"
    done
fi

[[ "$RUNFILE" != "" ]] && echo "Runfile: $RUNFILE";

outdir="$(pwd)/GROUP_STATS/$(whoami)/FCMAP/${GRPNAME}"

#####
#echo "DEBUG MODE!"
#exit 0;
#####

if [ $SMOOTH -eq 0 ]; then
    SMOOTH_HALF_F=0
else
    SMOOTH_HALF_F=$( echo 'scale=15;(.4412712/('$SMOOTH'/100))' | bc  | awk '{print int($1)}' );
fi

if [ "$SINGLEMAPS" !=  "" ]; then
    echo "***************************"
    echo "Creating individual maps..."
    echo "***************************"
    if [ "$SEPARATE" != "" ]; then
    	echo "creating individual maps for each run"
    	for subject in $SUBJECTS; do
	    if [ "$RUNFILE" != "" ]; then
	        echo "+++"
	    	if [ ! -r $subject/$RUNFILE ]; then
		    echo "*** NO RUNFILE ($RUNFILE) FOR ${subject}. Skipping... ***"
		    exit;
		fi
		
	    	runs=$(cat $subject/$RUNFILE | xargs);
	    else
    	    	runs=$(ls -d $subject/bold/0* );
	    fi
	    t=""
	    for run in $runs; do run=$(basename $run); t="${t}${run} "; done ;
	    t=$(echo $t)
	    echo "runs: $t"
	    echo "/cluster/animal/scripts/NRG-fc/functions/fc_map_process \"$subject\" \"$ROIs\" \"$ROInames\" $FRAMES \"$GRPNAME\" $SMOOTH_HALF_F \"$t\" TRUE"
	    /cluster/animal/scripts/NRG-fc/functions/fc_map_process "$subject" "$ROIs" "$ROInames" $FRAMES "$GRPNAME" $SMOOTH_HALF_F "$t" TRUE;
	done
    else
    	echo "/cluster/animal/scripts/NRG-fc/functions/fc_map_process \"$SUBJECTS\" \"$ROIs\" \"$ROInames\" $FRAMES \"$GRPNAME\" $SMOOTH_HALF_F;"
    	/cluster/animal/scripts/NRG-fc/functions/fc_map_process "$SUBJECTS" "$ROIs" "$ROInames" $FRAMES "$GRPNAME" $SMOOTH_HALF_F;
    fi
fi

if [ "$GROUPAVG" != "" ]; then
    echo "******************************"
    echo "*   Creating group map(s)    *";
    echo "******************************"

    # combined subject groups (if multiple)
    if [ "$SEPARATE" != "" ]; then
    	/cluster/animal/scripts/NRG-fc/functions/fc_map_combine "$SUBJECTS" "$ROIs" "$ROInames" $GRPNAME $SMOOTH_HALF_F TRUE $RUNFILE;
    else
    	echo "/cluster/animal/scripts/NRG-fc/functions/fc_map_combine "$SUBJECTS" "$ROIs" "$ROInames" $GRPNAME $SMOOTH_HALF_F;"
    	/cluster/animal/scripts/NRG-fc/functions/fc_map_combine "$SUBJECTS" "$ROIs" "$ROInames" $GRPNAME $SMOOTH_HALF_F;
    fi
fi
    
#########################################################
# run glm, group1 vs. group2 
# (only supports 2 groups right now)
# need to add variable support for FSGD!!!
#########################################################

if [[ $NUMSUBJECTFILES -eq 2 ]]; then
    echo "Processing GLM -- did you know GLM stands for gangsta lobster machine?"
    FSGD="/tmp/$$.fsgd"

    for roi in $ROInames; do
	filelist=""
	echo "GroupDescriptorFile     1" > $FSGD
	echo "Title FC_MAP_2GROUPS" >> $FSGD
	echo "Class ${SUBJECTGROUPNAMES[0]}" >> $FSGD
	echo "Class ${SUBJECTGROUPNAMES[1]}" >> $FSGD
	# TODO: variables? HELLO?!
    	for x in $(seq 0 $((${#SUBJECTGROUPS[*]} - 1))); do 
	    n=$(echo ${SUBJECTGROUPS[x]} | wc -w)
	    grp=${SUBJECTGROUPNAMES[x]}
	    odir=${outdir}_$grp
    	    file=$odir/N${n}_zfrm_${roi}.lst

	    for subj in $(echo ${SUBJECTGROUPS[x]}); do
		echo "Input $subj ${SUBJECTGROUPNAMES[x]}" >> $FSGD
	    done

	    # group average (this must run properly in order to continue)
	    if [ "$GROUPAVG" != "" ]; then
		/cluster/animal/scripts/NRG-fc/functions/fc_map_combine "${SUBJECTGROUPS[x]}" "$ROIs" "$ROInames" $GRPNAME $SMOOTH_HALF_F $grp;
    	    fi

	    # file list for each group
	    if [ -e $file ]; then
		# TODO: if we want to, we could also add this, which would correlate subgroup with measurements...
		#/cluster/animal/scripts/NRG-fc/functions/fc_map_meas $file $roi $outdir "$SUBJECTS" $MEASFILE
		filelist="$filelist $file"
	    else
		echo "Error: cannot find $file (should have been created by fc_map_combine"; exit 1;
	    fi
	done

	# temp. 4d file
	fslmerge -t /tmp/$$.nii.gz $(cat $filelist | xargs)

	echo "************"
	echo $FSGD
	echo "************"

	echo "1 -1" > /tmp/$roi.mat
	glmresults="$outdir/${SUBJECTGROUPNAMES[0]}_vs_${SUBJECTGROUPNAMES[1]}"
	mri_glmfit --y /tmp/$$.nii.gz --fsgd $FSGD doss --C /tmp/$roi.mat --glmdir $glmresults
    	mri_mask $glmresults/$roi/sig.mgh $BRAINMASK $outdir/${roi}_zfrm_${SUBJECTGROUPNAMES[0]}_vs_${SUBJECTGROUPNAMES[1]}.sig.nii.gz
	rm -f /tmp/$$.*
    done
fi
#########################################################


# Correlate connectivity maps with behavioral measures. 
if [[ "$MEASFILE" != "" ]]; then
    # check to see if group maps are available
    nsubs=$(echo $SUBJECTS | wc -w)
    for roi in $ROInames; do
    	file=$outdir/N${nsubs}_zfrm_${roi}.lst
    	if [ -r $file ]; then
	    /cluster/animal/scripts/NRG-fc/functions/fc_map_meas $file $roi $outdir "$SUBJECTS" $MEASFILE
	else
	    echo "Error: cannot find $outdir/N${nsubs}_zfrm_${roi}.lst. Cannot calculate behavioral correlation"
	fi
    done
fi

# Project to fsaverage ... TODO
#if [ "$FSPROJECT" != ""]; then
#   echo "Projecting z-transform map to fsaverage cortical surface..."
#   mri_vol2surf --mov 
#fi

if [ "$GROUPBIN" != "" ]; then
    echo "***************************"
    echo "Create binary group map...";
    echo "***************************"
    /cluster/animal/scripts/NRG-fc/functions/fc_map_combine_bin "$SUBJECTS" "$ROIs" "$ROInames" $THRESH "$GRPNAME" $SMOOTH_HALF_F;
fi
